package main;

import calculadora.Calculador;
import excepciones.MiException;

public class Main {

	public static void main(String[] args) throws MiException {

		System.out.println(Calculador.calcular2());

	}

}
